import pyttsx3
import datetime
import speech_recognition as sr
import wikipedia
import webbrowser
import os
import smtplib
import pyjokes
import subprocess
import sqlite3 as lite
from time import sleep
from email.message import EmailMessage
from credential import EMAIL_ADDRESS, EMAIL_PASSWORD    
 

engine = pyttsx3.init('sapi5')
voices = engine.getProperty('voices')
engine.setProperty('voice', voices[1].id)

def speak(audio):
    engine.say(audio)
    engine.runAndWait()


def wishme():
    speak("May I know your name please")
    query01 = takecommand().lower()
    con=lite.connect('history.db')
    with con:
        cur=con.cursor()
        cur.execute("CREATE TABLE IF NOT EXISTS Users(Name TEXT,Time TEXT)")
    str_time = datetime.datetime.now().strftime("%H:%M:%S")

    sql = "INSERT INTO Users (Name,Time) VALUES (?,?)"
    con.execute(sql, (query01,str_time,))
    con.commit()

    cur.execute("SELECT Name FROM Users")
    rows=cur.fetchall()
    # for row in rows:
    #     print(row)

    hour = int(datetime.datetime.now().hour)
    if hour >= 0 and hour < 12:
        speak("Good Morning")
    elif hour >= 12 and hour < 17:
        speak("Good Afternoon")
    else:
        speak("Good Evening")
    speak(f"Hey {query01} ,, RMX at your service")


def takecommand():
    ''' Takes Input from Microphone'''
    r = sr.Recognizer()
    with sr.Microphone() as source:
        print("Listening. . . . ")
        r.pause_threshold = 1
        audio = r.listen(source)
    try:
        print("Recognizing")
        query = r.recognize_google(audio, language="en-in")
        print(f"User Said: {query}")

    except Exception as e:
        print("Say that again")
        return "None"
    return query


def sendemail(to, content):
    msg = EmailMessage()
    msg['Subject'] = 'Autogenerated Mail '
    msg['From'] = EMAIL_ADDRESS
    msg['To'] = 'ritish20mohapatra@gmail.com'
    msg.set_content('Bot sent you!:'+content)

    msg.add_alternative("""\
		<!DOCTYPE html>
		<html>
			<body>
				<h1 style="color:SlateGray;">Bot sent you this!</h1>
			</body>
		</html>    
		""", subtype='html')

    with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp:
        smtp.login(EMAIL_ADDRESS, EMAIL_PASSWORD)
        smtp.send_message(msg)


def cycle():
    while True:
        query = takecommand().lower()

        if 'wikipedia' in query:
            speak("Searching wikipedia")
            query = query.replace("wikipedia", "")
            results = wikipedia.summary(query, sentences=2)
            speak("According to wikipedia ")
            print(results)
            speak(results)
        elif 'open youtube' in query:
            webbrowser.open("youtube.com")
        elif 'open google' in query:
            # webbrowser.open("google.com")
            webbrowser.open("google.com")
        elif 'open coursera' in query:
            webbrowser.open("coursera.org")
        elif 'joke' in query:
            speak(pyjokes.get_joke())
        elif 'introduce' in query:
            speak("I am RMX, I am born in Mumbai. my heart is india")
        elif 'play music' in query:
            music_location = 'D:\\Coding\\Coding in Py\\Py Proj\\RMX Voice\\Songs'
            songs = os.listdir(music_location)
            print(songs)
            os.startfile(os.path.join(music_location, songs[0]))
        elif 'time' in query:
            str_time = datetime.datetime.now().strftime("%H:%M:%S")
            speak(f"Hey Sparky ,, the Time is {str_time}") 
            # speak(f"sir indian standard time ko dhyaan rakhte hue  {str_time} hua he") 
        elif 'open code' in query:
            vsc_loc = '"C:\\Users\\Ritish Mohapatra\\Desktop\\Visual Studio Code"'
            os.startfile(vsc_loc)
        elif 'brave' in query:
            vsc_loc01 = '"C:\\Users\\Public\\Desktop\\Brave"'
            os.startfile(vsc_loc01)
        elif 'teams'in query:
            vsc_loc02 = '"C:\\Users\\Ritish Mohapatra\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Microsoft Teams"'
            os.startfile(vsc_loc02)
        elif 'notepad'in query:
            vsc_loc03 = '"C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Accessories\\Notepad"'
            os.startfile(vsc_loc03)
        elif 'WhatsApp' in query:
            vsc_loc04 = '"C:\\Users\\Ritish Mohapatra\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\WhatsApp\\WhatsApp"'
            os.startfile(vsc_loc04)
        elif 'microsoft PowerPoint'in query:
            vsc_loc05 = '"C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\PowerPoint"'
            os.startfile(vsc_loc05)
        elif 'microsoft word'in query:
            vsc_loc05 = '"C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Word"'
            os.startfile(vsc_loc05)
        # elif 'produce virus' in query:
        #     while True:
        #         subprocess.Popen('notepad')
        #         subprocess.Popen('calc')
        #         subprocess.Popen('mspaint')
        #         subprocess.Popen('explorer')
        #         subprocess.Popen('write')  
        #         sleep(.05)    
        elif 'shutdown' in query:
            os.system("shutdown /s /t 1")
        elif 'exit'in query:
            speak("Thanks for giving me your valuable time")
            exit() 
        elif 'email to sender' in query:
            try:
                speak("What Should I Say")
                content = takecommand()
                speak("Whom to send?")
                to = takecommand()
                sendemail=(to,content)
                speak("Email Sent")
            except Exception as e:
                print(e)
                speak("Email cannot be sent")